AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-sorbet

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false
