gem:
  # Add your `gem` command parameters here:
  #
  exclude:
  - 'aws-sdk-secretsmanager'
  - 'debug'
  - 'dotenv'
  - 'logger'
  - 'minitest-hooks'
  - 'mocha'
  - 'rubocop-sorbet'
  - 'sorbet-runtime'
  - 'tapioca'
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
