version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.4.2
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.5.6
            bundle install
            bundle exec rake
