#! /usr/bin/env ruby
# typed: true
# frozen_string_literal: true

require 'wachtwoord'

matcher = Wachtwoord::SecretNameMatcher.new
secret_name_in_file = T.let(false, T::Boolean)
$ARGV.each do |file_name|
  file_name = file_name.chomp
  names = Dotenv::Parser.call(File.read(file_name)).keys
  names.each do |name|
    next unless matcher.secret_name?(name)

    secret_name_in_file = true
    warn "potential secret in #{file_name} called #{name}"
  end
end

exit(1) if secret_name_in_file
