# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Aws::SecretsManager::Client; end
module ::Aws::SecretsManager::Errors::ResourceNotFoundException; end
class ::Rails::Railtie; end
module Minitest::Hooks; end

class Dotenv::Parser
  def call
  end

  def initialize(input)
  end
end
